import pendulum

from airflow import models
from airflow.models import Variable
from airflow.providers.google.cloud.transfers.postgres_to_gcs import PostgresToGCSOperator
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.contrib.operators.gcs_to_bq import GoogleCloudStorageToBigQueryOperator
from airflow.operators.bash import BashOperator
from datetime import datetime
import pytz

PROJECT_ID = 'kai-genai-prod'
SCHEMA = 'dashboard_material'
POSTGRES_CONNECTION_ID = 'kai_postgres'
TABLE = 'mara'
ALTER_TABLE = "general_material_data"
GCS_BUCKET = 'kai_smartsheet'
FILE_NAME = f'{TABLE}.parquet'

def push_current_timestamp():
    jakarta_tz = pytz.timezone('Asia/Jakarta')
    current_ts = datetime.now(jakarta_tz).strftime('%Y-%m-%d %H:%M:%S')
    return current_ts  # Push to XCom automatically


def build_query_and_run(**kwargs):
    ti = kwargs['ti']
    current_ts = ti.xcom_pull(task_ids='push_ts_task')

    query = f"""
        INSERT INTO {PROJECT_ID}.{SCHEMA}.{ALTER_TABLE} (client, material_number, created_on, name_of_person_who_created_the_object, date_of_last_change, name_of_person_who_changed_object, maintenance_status_of_complete_material, maintenance_status, flag_material_for_deletion_at_client_level, material_type, industry_sector, material_group, old_material_number, base_unit_of_measure, purchase_order_unit_of_measure, document_number_without_document_management_system, document_type_without_document_management_system, document_version_without_document_management_system, page_format_of_document_without_document_management_system, document_change_number_without_document_management_system, page_number_of_document_without_document_management_system, number_of_sheets_without_document_management_system, production_inspection_memo, page_format_of_production_memo, size_dimensions, basic_material, industry_standard_description_such_as_ansi_or_iso, laboratory_design_office, purchasing_value_key, gross_weight, net_weight, weight_unit, volume, volume_unit, container_requirements, storage_conditions, temperature_conditions_indicator, low_level_code, transportation_group, hazardous_material_number, division, competitor, european_article_number_ean_obsolete, quantity_number_of_gr_gi_slips_to_be_printed, procurement_rule, source_of_supply, season_category, label_type, label_form, deactivated, international_article_number_ean_upc, category_of_international_article_number_ean, length, width, height, unit_of_dimension_for_length_width_height, product_hierarchy, stock_transfer_net_change_costing, cad_indicator, qm_in_procurement_is_active, allowed_packaging_weight, unit_of_weight_allowed_packaging_weight, allowed_packaging_volume, volume_unit_allowed_packaging_volume, excess_weight_tolerance_for_handling_unit, excess_volume_tolerance_of_the_handling_unit, variable_purchase_order_unit_active, revision_level_has_been_assigned_to_the_material, configurable_material, batch_management_requirement_indicator, packaging_material_type, maximum_level_by_volume, stacking_factor, material_group_packaging_materials, authorization_group, valid_from_date, deletion_date, season_year, price_band_category, empties_bill_of_material, external_material_group, cross_plant_configurable_material, material_category, indicator_material_can_be_co_product, indicator_the_material_has_a_follow_up_material, pricing_reference_material, cross_plant_material_status, cross_distribution_chain_material_status, date_from_which_the_cross_plant_material_status_is_valid, date_from_which_the_x_distr_chain_material_status_is_valid, tax_classification_of_the_material, catalog_profile, minimum_remaining_shelf_life, total_shelf_life, storage_percentage, content_unit, net_contents, comparison_price_unit, is_r_labeling_material_grouping_deactivated_in_4_0, gross_contents, quantity_conversion_method, internal_object_number, environmentally_relevant, product_allocation_determination_procedure, pricing_profile_for_variants, material_qualifies_for_discount_in_kind, manufacturer_part_number, number_of_a_manufacturer, number_of_firm_s_own_internal_inventory_managed_material, manufacturer_part_profile, units_of_measure_usage, rollout_in_a_season, dangerous_goods_indicator_profile, indicator_highly_viscous, indicator_in_bulk_liquid, level_of_explicitness_for_serial_number, packaging_material_is_closed_packaging, indicator_approved_batch_record_required, assign_effectivity_parameter_values_override_change_numbers, material_completion_level, period_indicator_for_shelf_life_expiration_date, rounding_rule_for_calculation_of_sled, indicator_product_composition_printed_on_packaging, general_item_category_group, generic_material_with_logistical_variants, material_is_locked, relevant_for_configuration_management, assortment_list_type, expiration_date, global_trade_item_number_variant, material_number_of_the_generic_material_in_prepack_materials, reference_material_for_materials_packed_in_same_way, indicator_global_data_synchronization_relevant, acceptance_at_origin, standard_hu_type, pilferable, warehouse_storage_condition, warehouse_material_group, handling_indicator, relevant_for_hazardous_substances, handling_unit_type, variable_tare_weight, maximum_allowed_capacity_of_packaging_material, overcapacity_tolerance_of_the_handling_unit, maximum_packing_length_of_packaging_material, maximum_packing_width_of_packaging_material, maximum_packing_height_of_packaging_material, unit_of_measure_for_maximum_packing_length_width_height, country_of_origin_of_the_material, material_freight_group, quarantine_period, time_unit_for_quarantine_period, quality_inspection_group, serial_number_profile, form_name, ewm_cw_logistics_unit_of_measure, ewm_cw_material_is_a_catch_weight_material, ewm_cw_catch_weight_profile_for_entering_cw_quantity, ewm_cw_catch_weight_tolerance_group_for_ewm, adjustment_profile, id_for_an_intellectual_property_crm_product, variant_price_allowed_for_material_master, medium, indicator_contains_non_textile_parts_of_animal_origin, indicator_new_textile_composition_function, anp_code, loading_units, loading_unit_group_is_beverage, structure_category_for_material_relationship, tolerance_type_id, counting_group, dsd_grouping, material_may_be_tilted_vehicle_space_optimization, stacking_not_allowed_vso, bottom_layer_vehicle_space_optimization, top_layer_vso, stacking_factor_vehicle_space_optimization, load_without_packaging_material_vso, permissible_overhang_depth_of_packaging_material_vso, permissible_overhang_width_of_shipping_material_vso, maximum_stacking_height_of_the_packaging_material_vso, minimum_stacking_height_of_the_packaging_material_vso, tolerance_to_exceed_the_max_stacking_height_vso, number_of_materials_for_each_closed_pkm_vso, unit_of_measure_vehicle_space_optimization, closed_packaging_material_required_vso, packaging_code, dangerous_goods_packaging_status, material_condition_management, return_code, return_to_logistics_level, nato_stock_number, fff_class, supersession_chain_number, creation_status_seasonal_procurement, internal_charactieristic_number_for_color_characteristics, internal_char_number_for_characteristics_for_main_sizes, internal_char_number_for_characteristics_for_second_sizes, characteristic_value_for_colors_of_variants, characteristic_value_for_main_sizes_of_variants, characteristic_value_for_second_size_for_variants, characteristic_value_for_evaluation_purposes, care_codes_such_as_washing_code_ironing_code_etc, brand, fiber_code_for_textiles_component_1, percentage_share_of_fiber_component_1, fiber_code_for_textiles_component_2, percentage_share_of_fiber_component_2, fiber_code_for_textiles_component_3, percentage_share_of_fiber_component_3, fiber_code_for_textiles_component_4, percentage_share_of_fiber_component_4, fiber_code_for_textiles_component_5, percentage_share_of_fiber_component_5, fashion_grade, physical_commodity, classification_of_segmentation_structure_group, coverage_segment_allocation, segmentation_status, segmentation_scope, release_strategy_for_segmentation, material_group_attribute_1, material_group_attribute_2, material_group_attribute_3, season_level, season_indicator, season_category_mid, product_segmentation_code, tanggal_atau_waktu_pembaruan_terakhir_data, last_insert_to_bigquery)
        SELECT
            CAST(MANDT as STRING) as client,
            CAST(MATNR as STRING) as material_number,
            CAST(ERSDA as STRING) as created_on,
            CAST(ERNAM as STRING) as name_of_person_who_created_the_object,
            CAST(LAEDA as STRING) as date_of_last_change,
            CAST(AENAM as STRING) as name_of_person_who_changed_object,
            CAST(VPSTA as STRING) as maintenance_status_of_complete_material,
            CAST(PSTAT as STRING) as maintenance_status,
            CAST(LVORM as STRING) as flag_material_for_deletion_at_client_level,
            CAST(MTART as STRING) as material_type,
            CAST(MBRSH as STRING) as industry_sector,
            CAST(MATKL as STRING) as material_group,
            CAST(BISMT as STRING) as old_material_number,
            CAST(MEINS as STRING) as base_unit_of_measure,
            CAST(BSTME as STRING) as purchase_order_unit_of_measure,
            CAST(ZEINR as STRING) as document_number_without_document_management_system,
            CAST(ZEIAR as STRING) as document_type_without_document_management_system,
            CAST(ZEIVR as STRING) as document_version_without_document_management_system,
            CAST(ZEIFO as STRING) as page_format_of_document_without_document_management_system,
            CAST(AESZN as STRING) as document_change_number_without_document_management_system,
            CAST(BLATT as STRING) as page_number_of_document_without_document_management_system,
            CAST(BLANZ as STRING) as number_of_sheets_without_document_management_system,
            CAST(FERTH as STRING) as production_inspection_memo,
            CAST(FORMT as STRING) as page_format_of_production_memo,
            CAST(GROES as STRING) as size_dimensions,
            CAST(WRKST as STRING) as basic_material,
            CAST(NORMT as STRING) as industry_standard_description_such_as_ansi_or_iso,
            CAST(LABOR as STRING) as laboratory_design_office,
            CAST(EKWSL as STRING) as purchasing_value_key,
            CAST(BRGEW as NUMERIC) as gross_weight,
            CAST(NTGEW as NUMERIC) as net_weight,
            CAST(GEWEI as STRING) as weight_unit,
            CAST(VOLUM as NUMERIC) as volume,
            CAST(VOLEH as STRING) as volume_unit,
            CAST(BEHVO as STRING) as container_requirements,
            CAST(RAUBE as STRING) as storage_conditions,
            CAST(TEMPB as STRING) as temperature_conditions_indicator,
            CAST(DISST as STRING) as low_level_code,
            CAST(TRAGR as STRING) as transportation_group,
            CAST(STOFF as STRING) as hazardous_material_number,
            CAST(SPART as STRING) as division,
            CAST(KUNNR as STRING) as competitor,
            CAST(EANNR as STRING) as european_article_number_ean_obsolete,
            CAST(WESCH as NUMERIC) as quantity_number_of_gr_gi_slips_to_be_printed,
            CAST(BWVOR as STRING) as procurement_rule,
            CAST(BWSCL as STRING) as source_of_supply,
            CAST(SAISO as STRING) as season_category,
            CAST(ETIAR as STRING) as label_type,
            CAST(ETIFO as STRING) as label_form,
            CAST(ENTAR as STRING) as deactivated,
            CAST(EAN11 as STRING) as international_article_number_ean_upc,
            CAST(NUMTP as STRING) as category_of_international_article_number_ean,
            CAST(LAENG as NUMERIC) as length,
            CAST(BREIT as NUMERIC) as width,
            CAST(HOEHE as NUMERIC) as height,
            CAST(MEABM as STRING) as unit_of_dimension_for_length_width_height,
            CAST(PRDHA as STRING) as product_hierarchy,
            CAST(AEKLK as STRING) as stock_transfer_net_change_costing,
            CAST(CADKZ as STRING) as cad_indicator,
            CAST(QMPUR as STRING) as qm_in_procurement_is_active,
            CAST(ERGEW as NUMERIC) as allowed_packaging_weight,
            CAST(ERGEI as STRING) as unit_of_weight_allowed_packaging_weight,
            CAST(ERVOL as NUMERIC) as allowed_packaging_volume,
            CAST(ERVOE as STRING) as volume_unit_allowed_packaging_volume,
            CAST(GEWTO as NUMERIC) as excess_weight_tolerance_for_handling_unit,
            CAST(VOLTO as NUMERIC) as excess_volume_tolerance_of_the_handling_unit,
            CAST(VABME as STRING) as variable_purchase_order_unit_active,
            CAST(KZREV as STRING) as revision_level_has_been_assigned_to_the_material,
            CAST(KZKFG as STRING) as configurable_material,
            CAST(XCHPF as STRING) as batch_management_requirement_indicator,
            CAST(VHART as STRING) as packaging_material_type,
            CAST(FUELG as NUMERIC) as maximum_level_by_volume,
            CAST(STFAK as INTEGER) as stacking_factor,
            CAST(MAGRV as STRING) as material_group_packaging_materials,
            CAST(BEGRU as STRING) as authorization_group,
            CAST(DATAB as STRING) as valid_from_date,
            CAST(LIQDT as STRING) as deletion_date,
            CAST(SAISJ as STRING) as season_year,
            CAST(PLGTP as STRING) as price_band_category,
            CAST(MLGUT as STRING) as empties_bill_of_material,
            CAST(EXTWG as STRING) as external_material_group,
            CAST(SATNR as STRING) as cross_plant_configurable_material,
            CAST(ATTYP as STRING) as material_category,
            CAST(KZKUP as STRING) as indicator_material_can_be_co_product,
            CAST(KZNFM as STRING) as indicator_the_material_has_a_follow_up_material,
            CAST(PMATA as STRING) as pricing_reference_material,
            CAST(MSTAE as STRING) as cross_plant_material_status,
            CAST(MSTAV as STRING) as cross_distribution_chain_material_status,
            CAST(MSTDE as STRING) as date_from_which_the_cross_plant_material_status_is_valid,
            CAST(MSTDV as STRING) as date_from_which_the_x_distr_chain_material_status_is_valid,
            CAST(TAKLV as STRING) as tax_classification_of_the_material,
            CAST(RBNRM as STRING) as catalog_profile,
            CAST(MHDRZ as NUMERIC) as minimum_remaining_shelf_life,
            CAST(MHDHB as NUMERIC) as total_shelf_life,
            CAST(MHDLP as NUMERIC) as storage_percentage,
            CAST(INHME as STRING) as content_unit,
            CAST(INHAL as NUMERIC) as net_contents,
            CAST(VPREH as NUMERIC) as comparison_price_unit,
            CAST(ETIAG as STRING) as is_r_labeling_material_grouping_deactivated_in_4_0,
            CAST(INHBR as NUMERIC) as gross_contents,
            CAST(CMETH as STRING) as quantity_conversion_method,
            CAST(CUOBF as STRING) as internal_object_number,
            CAST(KZUMW as STRING) as environmentally_relevant,
            CAST(KOSCH as STRING) as product_allocation_determination_procedure,
            CAST(SPROF as STRING) as pricing_profile_for_variants,
            CAST(NRFHG as STRING) as material_qualifies_for_discount_in_kind,
            CAST(MFRPN as STRING) as manufacturer_part_number,
            CAST(MFRNR as STRING) as number_of_a_manufacturer,
            CAST(BMATN as STRING) as number_of_firm_s_own_internal_inventory_managed_material,
            CAST(MPROF as STRING) as manufacturer_part_profile,
            CAST(KZWSM as STRING) as units_of_measure_usage,
            CAST(SAITY as STRING) as rollout_in_a_season,
            CAST(PROFL as STRING) as dangerous_goods_indicator_profile,
            CAST(IHIVI as STRING) as indicator_highly_viscous,
            CAST(ILOOS as STRING) as indicator_in_bulk_liquid,
            CAST(SERLV as STRING) as level_of_explicitness_for_serial_number,
            CAST(KZGVH as STRING) as packaging_material_is_closed_packaging,
            CAST(XGCHP as STRING) as indicator_approved_batch_record_required,
            CAST(KZEFF as STRING) as assign_effectivity_parameter_values_override_change_numbers,
            CAST(COMPL as STRING) as material_completion_level,
            CAST(IPRKZ as STRING) as period_indicator_for_shelf_life_expiration_date,
            CAST(RDMHD as STRING) as rounding_rule_for_calculation_of_sled,
            CAST(PRZUS as STRING) as indicator_product_composition_printed_on_packaging,
            CAST(MTPOS_MARA as STRING) as general_item_category_group,
            CAST(BFLME as STRING) as generic_material_with_logistical_variants,
            CAST(MATFI as STRING) as material_is_locked,
            CAST(CMREL as STRING) as relevant_for_configuration_management,
            CAST(BBTYP as STRING) as assortment_list_type,
            CAST(SLED_BBD as STRING) as expiration_date,
            CAST(GTIN_VARIANT as STRING) as global_trade_item_number_variant,
            CAST(GENNR as STRING) as material_number_of_the_generic_material_in_prepack_materials,
            CAST(RMATP as STRING) as reference_material_for_materials_packed_in_same_way,
            CAST(GDS_RELEVANT as STRING) as indicator_global_data_synchronization_relevant,
            CAST(WEORA as STRING) as acceptance_at_origin,
            CAST(HUTYP_DFLT as STRING) as standard_hu_type,
            CAST(PILFERABLE as STRING) as pilferable,
            CAST(WHSTC as STRING) as warehouse_storage_condition,
            CAST(WHMATGR as STRING) as warehouse_material_group,
            CAST(HNDLCODE as STRING) as handling_indicator,
            CAST(HAZMAT as STRING) as relevant_for_hazardous_substances,
            CAST(HUTYP as STRING) as handling_unit_type,
            CAST(TARE_VAR as STRING) as variable_tare_weight,
            CAST(MAXC as NUMERIC) as maximum_allowed_capacity_of_packaging_material,
            CAST(MAXC_TOL as NUMERIC) as overcapacity_tolerance_of_the_handling_unit,
            CAST(MAXL as NUMERIC) as maximum_packing_length_of_packaging_material,
            CAST(MAXB as NUMERIC) as maximum_packing_width_of_packaging_material,
            CAST(MAXH as NUMERIC) as maximum_packing_height_of_packaging_material,
            CAST(MAXDIM_UOM as STRING) as unit_of_measure_for_maximum_packing_length_width_height,
            CAST(HERKL as STRING) as country_of_origin_of_the_material,
            CAST(MFRGR as STRING) as material_freight_group,
            CAST(QQTIME as NUMERIC) as quarantine_period,
            CAST(QQTIMEUOM as STRING) as time_unit_for_quarantine_period,
            CAST(QGRP as STRING) as quality_inspection_group,
            CAST(SERIAL as STRING) as serial_number_profile,
            CAST(PS_SMARTFORM as STRING) as form_name,
            CAST(LOGUNIT as STRING) as ewm_cw_logistics_unit_of_measure,
            CAST(CWQREL as STRING) as ewm_cw_material_is_a_catch_weight_material,
            CAST(CWQPROC as STRING) as ewm_cw_catch_weight_profile_for_entering_cw_quantity,
            CAST(CWQTOLGR as STRING) as ewm_cw_catch_weight_tolerance_group_for_ewm,
            CAST(ADPROF as STRING) as adjustment_profile,
            CAST(IPMIPPRODUCT as STRING) as id_for_an_intellectual_property_crm_product,
            CAST(ALLOW_PMAT_IGNO as STRING) as variant_price_allowed_for_material_master,
            CAST(MEDIUM as STRING) as medium,
            CAST(ANIMAL_ORIGIN as STRING) as indicator_contains_non_textile_parts_of_animal_origin,
            CAST(TEXTILE_COMP_IND as STRING) as indicator_new_textile_composition_function,
            CAST(ANP as STRING) as anp_code,
            CAST(BEV1_LULEINH as STRING) as loading_units,
            CAST(BEV1_LULDEGRP as STRING) as loading_unit_group_is_beverage,
            CAST(BEV1_NESTRUCCAT as STRING) as structure_category_for_material_relationship,
            CAST(DSD_SL_TOLTYP as STRING) as tolerance_type_id,
            CAST(DSD_SV_CNT_GRP as STRING) as counting_group,
            CAST(DSD_VC_GROUP as STRING) as dsd_grouping,
            CAST(VSO_R_TILT_IND as STRING) as material_may_be_tilted_vehicle_space_optimization,
            CAST(VSO_R_STACK_IND as STRING) as stacking_not_allowed_vso,
            CAST(VSO_R_BOT_IND as STRING) as bottom_layer_vehicle_space_optimization,
            CAST(VSO_R_TOP_IND as STRING) as top_layer_vso,
            CAST(VSO_R_STACK_NO as STRING) as stacking_factor_vehicle_space_optimization,
            CAST(VSO_R_PAL_IND as STRING) as load_without_packaging_material_vso,
            CAST(VSO_R_PAL_OVR_D as NUMERIC) as permissible_overhang_depth_of_packaging_material_vso,
            CAST(VSO_R_PAL_OVR_W as NUMERIC) as permissible_overhang_width_of_shipping_material_vso,
            CAST(VSO_R_PAL_B_HT as NUMERIC) as maximum_stacking_height_of_the_packaging_material_vso,
            CAST(VSO_R_PAL_MIN_H as NUMERIC) as minimum_stacking_height_of_the_packaging_material_vso,
            CAST(VSO_R_TOL_B_HT as NUMERIC) as tolerance_to_exceed_the_max_stacking_height_vso,
            CAST(VSO_R_NO_P_GVH as STRING) as number_of_materials_for_each_closed_pkm_vso,
            CAST(VSO_R_QUAN_UNIT as STRING) as unit_of_measure_vehicle_space_optimization,
            CAST(VSO_R_KZGVH_IND as STRING) as closed_packaging_material_required_vso,
            CAST(PACKCODE as STRING) as packaging_code,
            CAST(DG_PACK_STATUS as STRING) as dangerous_goods_packaging_status,
            CAST(MCOND as STRING) as material_condition_management,
            CAST(RETDELC as STRING) as return_code,
            CAST(LOGLEV_RETO as STRING) as return_to_logistics_level,
            CAST(NSNID as STRING) as nato_stock_number,
            CAST(IMATN as STRING) as fff_class,
            CAST(PICNUM as STRING) as supersession_chain_number,
            CAST(BSTAT as STRING) as creation_status_seasonal_procurement,
            CAST(COLOR_ATINN as STRING) as internal_charactieristic_number_for_color_characteristics,
            CAST(SIZE1_ATINN as STRING) as internal_char_number_for_characteristics_for_main_sizes,
            CAST(SIZE2_ATINN as STRING) as internal_char_number_for_characteristics_for_second_sizes,
            CAST(COLOR as STRING) as characteristic_value_for_colors_of_variants,
            CAST(SIZE1 as STRING) as characteristic_value_for_main_sizes_of_variants,
            CAST(SIZE2 as STRING) as characteristic_value_for_second_size_for_variants,
            CAST(FREE_CHAR as STRING) as characteristic_value_for_evaluation_purposes,
            CAST(CARE_CODE as STRING) as care_codes_such_as_washing_code_ironing_code_etc,
            CAST(BRAND_ID as STRING) as brand,
            CAST(FIBER_CODE1 as STRING) as fiber_code_for_textiles_component_1,
            CAST(FIBER_PART1 as STRING) as percentage_share_of_fiber_component_1,
            CAST(FIBER_CODE2 as STRING) as fiber_code_for_textiles_component_2,
            CAST(FIBER_PART2 as STRING) as percentage_share_of_fiber_component_2,
            CAST(FIBER_CODE3 as STRING) as fiber_code_for_textiles_component_3,
            CAST(FIBER_PART3 as STRING) as percentage_share_of_fiber_component_3,
            CAST(FIBER_CODE4 as STRING) as fiber_code_for_textiles_component_4,
            CAST(FIBER_PART4 as STRING) as percentage_share_of_fiber_component_4,
            CAST(FIBER_CODE5 as STRING) as fiber_code_for_textiles_component_5,
            CAST(FIBER_PART5 as STRING) as percentage_share_of_fiber_component_5,
            CAST(FASHGRD as STRING) as fashion_grade,
            CAST(COMMODITY as STRING) as physical_commodity,
            CAST(SGT_CSGR as STRING) as classification_of_segmentation_structure_group,
            CAST(SGT_COVSA as STRING) as coverage_segment_allocation,
            CAST(SGT_STAT as STRING) as segmentation_status,
            CAST(SGT_SCOPE as STRING) as segmentation_scope,
            CAST(SGT_REL as STRING) as release_strategy_for_segmentation,
            CAST(FSH_MG_AT1 as STRING) as material_group_attribute_1,
            CAST(FSH_MG_AT2 as STRING) as material_group_attribute_2,
            CAST(FSH_MG_AT3 as STRING) as material_group_attribute_3,
            CAST(FSH_SEALV as STRING) as season_level,
            CAST(FSH_SEAIM as STRING) as season_indicator,
            CAST(FSH_SC_MID as STRING) as season_category_mid,
            CAST(PSM_CODE as STRING) as product_segmentation_code,
            CAST(last_update as DATETIME) as tanggal_atau_waktu_pembaruan_terakhir_data,
            DATETIME('{current_ts}') AS last_insert_to_bigquery
        FROM bq_landing_zone.{SCHEMA}_{TABLE};
    """

    # Execute pakai BigQueryInsertJobOperator
    BigQueryInsertJobOperator(
        task_id='load_to_refined_zone',
        gcp_conn_id='kai_genai_prod',
        configuration={
            "query": {
                "query": query,
                "useLegacySql": False,
            }
        },
        dag=kwargs['dag']
    ).execute(context=kwargs)
    
with models.DAG(
    'dashboard_material-mara',
    description="Doing incremental load from PostgreSQL to GCS",
    start_date=pendulum.datetime(2024, 9, 30, tz="Asia/Jakarta"),
    schedule_interval='* 1 * * *',
    max_active_runs=1,
    catchup=False,
    tags=['Gen-AI', 'dashboard_material', 'refined'],
) as tanggal_atau_waktu_pembaruan_terakhir_data:

    dump_from_postgres_to_gcs = PostgresToGCSOperator(
        task_id='dump_from_postgres_to_gcs',
        postgres_conn_id=POSTGRES_CONNECTION_ID,
        sql=f"""
        SELECT
            "MANDT"::TEXT,
            "MATNR"::TEXT,
            "ERSDA"::TEXT,
            "ERNAM"::TEXT,
            "LAEDA"::TEXT,
            "AENAM"::TEXT,
            "VPSTA"::TEXT,
            "PSTAT"::TEXT,
            "LVORM"::TEXT,
            "MTART"::TEXT,
            "MBRSH"::TEXT,
            "MATKL"::TEXT,
            "BISMT"::TEXT,
            "MEINS"::TEXT,
            "BSTME"::TEXT,
            "ZEINR"::TEXT,
            "ZEIAR"::TEXT,
            "ZEIVR"::TEXT,
            "ZEIFO"::TEXT,
            "AESZN"::TEXT,
            "BLATT"::TEXT,
            "BLANZ"::TEXT,
            "FERTH"::TEXT,
            "FORMT"::TEXT,
            "GROES"::TEXT,
            "WRKST"::TEXT,
            "NORMT"::TEXT,
            "LABOR"::TEXT,
            "EKWSL"::TEXT,
            "BRGEW"::NUMERIC,
            "NTGEW"::NUMERIC,
            "GEWEI"::TEXT,
            "VOLUM"::NUMERIC,
            "VOLEH"::TEXT,
            "BEHVO"::TEXT,
            "RAUBE"::TEXT,
            "TEMPB"::TEXT,
            "DISST"::TEXT,
            "TRAGR"::TEXT,
            "STOFF"::TEXT,
            "SPART"::TEXT,
            "KUNNR"::TEXT,
            "EANNR"::TEXT,
            "WESCH"::NUMERIC,
            "BWVOR"::TEXT,
            "BWSCL"::TEXT,
            "SAISO"::TEXT,
            "ETIAR"::TEXT,
            "ETIFO"::TEXT,
            "ENTAR"::TEXT,
            "EAN11"::TEXT,
            "NUMTP"::TEXT,
            "LAENG"::NUMERIC,
            "BREIT"::NUMERIC,
            "HOEHE"::NUMERIC,
            "MEABM"::TEXT,
            "PRDHA"::TEXT,
            "AEKLK"::TEXT,
            "CADKZ"::TEXT,
            "QMPUR"::TEXT,
            "ERGEW"::NUMERIC,
            "ERGEI"::TEXT,
            "ERVOL"::NUMERIC,
            "ERVOE"::TEXT,
            "GEWTO"::NUMERIC,
            "VOLTO"::NUMERIC,
            "VABME"::TEXT,
            "KZREV"::TEXT,
            "KZKFG"::TEXT,
            "XCHPF"::TEXT,
            "VHART"::TEXT,
            "FUELG"::NUMERIC,
            "STFAK"::INTEGER,
            "MAGRV"::TEXT,
            "BEGRU"::TEXT,
            "DATAB"::TEXT,
            "LIQDT"::TEXT,
            "SAISJ"::TEXT,
            "PLGTP"::TEXT,
            "MLGUT"::TEXT,
            "EXTWG"::TEXT,
            "SATNR"::TEXT,
            "ATTYP"::TEXT,
            "KZKUP"::TEXT,
            "KZNFM"::TEXT,
            "PMATA"::TEXT,
            "MSTAE"::TEXT,
            "MSTAV"::TEXT,
            "MSTDE"::TEXT,
            "MSTDV"::TEXT,
            "TAKLV"::TEXT,
            "RBNRM"::TEXT,
            "MHDRZ"::NUMERIC,
            "MHDHB"::NUMERIC,
            "MHDLP"::NUMERIC,
            "INHME"::TEXT,
            "INHAL"::NUMERIC,
            "VPREH"::NUMERIC,
            "ETIAG"::TEXT,
            "INHBR"::NUMERIC,
            "CMETH"::TEXT,
            "CUOBF"::TEXT,
            "KZUMW"::TEXT,
            "KOSCH"::TEXT,
            "SPROF"::TEXT,
            "NRFHG"::TEXT,
            "MFRPN"::TEXT,
            "MFRNR"::TEXT,
            "BMATN"::TEXT,
            "MPROF"::TEXT,
            "KZWSM"::TEXT,
            "SAITY"::TEXT,
            "PROFL"::TEXT,
            "IHIVI"::TEXT,
            "ILOOS"::TEXT,
            "SERLV"::TEXT,
            "KZGVH"::TEXT,
            "XGCHP"::TEXT,
            "KZEFF"::TEXT,
            "COMPL"::TEXT,
            "IPRKZ"::TEXT,
            "RDMHD"::TEXT,
            "PRZUS"::TEXT,
            "MTPOS_MARA"::TEXT,
            "BFLME"::TEXT,
            "MATFI"::TEXT,
            "CMREL"::TEXT,
            "BBTYP"::TEXT,
            "SLED_BBD"::TEXT,
            "GTIN_VARIANT"::TEXT,
            "GENNR"::TEXT,
            "RMATP"::TEXT,
            "GDS_RELEVANT"::TEXT,
            "WEORA"::TEXT,
            "HUTYP_DFLT"::TEXT,
            "PILFERABLE"::TEXT,
            "WHSTC"::TEXT,
            "WHMATGR"::TEXT,
            "HNDLCODE"::TEXT,
            "HAZMAT"::TEXT,
            "HUTYP"::TEXT,
            "TARE_VAR"::TEXT,
            "MAXC"::NUMERIC,
            "MAXC_TOL"::NUMERIC,
            "MAXL"::NUMERIC,
            "MAXB"::NUMERIC,
            "MAXH"::NUMERIC,
            "MAXDIM_UOM"::TEXT,
            "HERKL"::TEXT,
            "MFRGR"::TEXT,
            "QQTIME"::NUMERIC,
            "QQTIMEUOM"::TEXT,
            "QGRP"::TEXT,
            "SERIAL"::TEXT,
            "PS_SMARTFORM"::TEXT,
            "LOGUNIT"::TEXT,
            "CWQREL"::TEXT,
            "CWQPROC"::TEXT,
            "CWQTOLGR"::TEXT,
            "ADPROF"::TEXT,
            "IPMIPPRODUCT"::TEXT,
            "ALLOW_PMAT_IGNO"::TEXT,
            "MEDIUM"::TEXT,
            "ANIMAL_ORIGIN"::TEXT,
            "TEXTILE_COMP_IND"::TEXT,
            "ANP"::TEXT,
            "/BEV1/LULEINH"::TEXT as "BEV1_LULEINH",
            "/BEV1/LULDEGRP"::TEXT as "BEV1_LULDEGRP",
            "/BEV1/NESTRUCCAT"::TEXT as "BEV1_NESTRUCCAT",
            "/DSD/SL_TOLTYP"::TEXT as "DSD_SL_TOLTYP",
            "/DSD/SV_CNT_GRP"::TEXT as "DSD_SV_CNT_GRP",
            "/DSD/VC_GROUP"::TEXT as "DSD_VC_GROUP",
            "/VSO/R_TILT_IND"::TEXT as "VSO_R_TILT_IND",
            "/VSO/R_STACK_IND"::TEXT as "VSO_R_STACK_IND",
            "/VSO/R_BOT_IND"::TEXT as "VSO_R_BOT_IND",
            "/VSO/R_TOP_IND"::TEXT as "VSO_R_TOP_IND",
            "/VSO/R_STACK_NO"::TEXT as "VSO_R_STACK_NO",
            "/VSO/R_PAL_IND"::TEXT as "VSO_R_PAL_IND",
            "/VSO/R_PAL_OVR_D"::NUMERIC as "VSO_R_PAL_OVR_D",
            "/VSO/R_PAL_OVR_W"::NUMERIC as "VSO_R_PAL_OVR_W",
            "/VSO/R_PAL_B_HT"::NUMERIC as "VSO_R_PAL_B_HT",
            "/VSO/R_PAL_MIN_H"::NUMERIC as "VSO_R_PAL_MIN_H",
            "/VSO/R_TOL_B_HT"::NUMERIC as "VSO_R_TOL_B_HT",
            "/VSO/R_NO_P_GVH"::TEXT as "VSO_R_NO_P_GVH",
            "/VSO/R_QUAN_UNIT"::TEXT as "VSO_R_QUAN_UNIT",
            "/VSO/R_KZGVH_IND"::TEXT as "VSO_R_KZGVH_IND",
            "PACKCODE"::TEXT,
            "DG_PACK_STATUS"::TEXT,
            "MCOND"::TEXT,
            "RETDELC"::TEXT,
            "LOGLEV_RETO"::TEXT,
            "NSNID"::TEXT,
            "IMATN"::TEXT,
            "PICNUM"::TEXT,
            "BSTAT"::TEXT,
            "COLOR_ATINN"::TEXT,
            "SIZE1_ATINN"::TEXT,
            "SIZE2_ATINN"::TEXT,
            "COLOR"::TEXT,
            "SIZE1"::TEXT,
            "SIZE2"::TEXT,
            "FREE_CHAR"::TEXT,
            "CARE_CODE"::TEXT,
            "BRAND_ID"::TEXT,
            "FIBER_CODE1"::TEXT,
            "FIBER_PART1"::TEXT,
            "FIBER_CODE2"::TEXT,
            "FIBER_PART2"::TEXT,
            "FIBER_CODE3"::TEXT,
            "FIBER_PART3"::TEXT,
            "FIBER_CODE4"::TEXT,
            "FIBER_PART4"::TEXT,
            "FIBER_CODE5"::TEXT,
            "FIBER_PART5"::TEXT,
            "FASHGRD"::TEXT,
            "COMMODITY"::TEXT,
            "SGT_CSGR"::TEXT,
            "SGT_COVSA"::TEXT,
            "SGT_STAT"::TEXT,
            "SGT_SCOPE"::TEXT,
            "SGT_REL"::TEXT,
            "FSH_MG_AT1"::TEXT,
            "FSH_MG_AT2"::TEXT,
            "FSH_MG_AT3"::TEXT,
            "FSH_SEALV"::TEXT,
            "FSH_SEAIM"::TEXT,
            "FSH_SC_MID"::TEXT,
            "PSM_CODE"::TEXT,
            last_update::TEXT
        FROM {SCHEMA}.{TABLE};
        """,
        bucket=GCS_BUCKET,
        filename=f'{SCHEMA}/{TABLE}/{FILE_NAME}',  # Nama file yang disimpan di GCS
        export_format='parquet',
        gcp_conn_id='kai_genai_prod',
        approx_max_file_size_bytes=50 * 1024 * 1024, # split 50 MB
        # parquet_row_group_size=1000000,
    )

    load_to_bigquery = GoogleCloudStorageToBigQueryOperator(
        task_id='load_to_bigquery',
        bucket=GCS_BUCKET,
        source_objects=f'{SCHEMA}/{TABLE}/{FILE_NAME}',
        source_format='parquet',
        destination_project_dataset_table=f'{PROJECT_ID}.bq_landing_zone.{SCHEMA}_{TABLE}', # Dataset harus dibuat terlebih dahulu
        write_disposition='WRITE_TRUNCATE', # WRITE_TRUNCATE | WRITE_EMPTY
        skip_leading_rows=1,
        autodetect=True,
        gcp_conn_id='kai_genai_prod'
    )

    push_ts_task = PythonOperator(
        task_id='push_ts_task',
        python_callable=push_current_timestamp,
        provide_context=True
    )

    build_query_task = PythonOperator(
        task_id='build_query_task',
        python_callable=build_query_and_run,
        provide_context=True
    )

    show_progress = BashOperator(
        task_id='show_progress',
        bash_command='echo DAG finished at {{ ts_nodash }}'
    )

    # Dependency
    dump_from_postgres_to_gcs >> load_to_bigquery >> push_ts_task >> build_query_task >> show_progress
