import pendulum

from airflow import models
from airflow.models import Variable
from airflow.providers.google.cloud.transfers.postgres_to_gcs import PostgresToGCSOperator
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.contrib.operators.gcs_to_bq import GoogleCloudStorageToBigQueryOperator
from airflow.operators.bash import BashOperator
from datetime import datetime
import pytz

PROJECT_ID = 'kai-genai-prod'
SCHEMA = 'dashboard_material'
POSTGRES_CONNECTION_ID = 'kai_postgres'
TABLE = 'mseg'
ALTER_TABLE = "document_segment_material"
GCS_BUCKET = 'kai_sap'
FILE_NAME = f'{TABLE}.parquet_{{}}'

def push_current_timestamp():
    jakarta_tz = pytz.timezone('Asia/Jakarta')
    current_ts = datetime.now(jakarta_tz).strftime('%Y-%m-%d %H:%M:%S')
    return current_ts  # Push to XCom automatically


def build_query_and_run(**kwargs):
    ti = kwargs['ti']
    current_ts = ti.xcom_pull(task_ids='push_ts_task')

    query = f"""
        INSERT INTO {PROJECT_ID}.{SCHEMA}.{ALTER_TABLE} (mandt, mblnr, mjahr, zeile, line_id, parent_id, line_depth, maa_urzei, bwart, xauto, matnr, werks, lgort, charg, insmk, zusch, zustd, sobkz, lifnr, kunnr, kdauf, kdpos, kdein, plpla, shkzg, waers, dmbtr, bnbtr, bualt, shkum, dmbum, bwtar, menge, meins, erfmg, erfme, bpmng, bprme, ebeln, ebelp, lfbja, lfbnr, lfpos, sjahr, smbln, smblp, elikz, sgtxt, equnr, wempf, ablad, gsber, kokrs, pargb, parbu, kostl, projn, aufnr, anln1, anln2, xskst, xsauf, xspro, xserg, gjahr, xruem, xruej, bukrs, belnr, buzei, belum, buzum, rsnum, rspos, kzear, pbamg, kzstr, ummat, umwrk, umlgo, umcha, umzst, umzus, umbar, umsok, kzbew, kzvbr, kzzug, weunb, palan, lgnum, lgtyp, lgpla, bestq, bwlvs, tbnum, tbpos, xblvs, vschn, nschn, dypla, ubnum, tbpri, tanum, weanz, grund, evers, evere, imkey, kstrg, paobjnr, prctr, ps_psp_pnr, nplnr, aufpl, aplzl, aufps, vptnr, fipos, sakto, bstmg, bstme, xwsbr, emlif, exbwr, vkwrt, aktnr, zekkn, vfdat, cuobj_ch, exvkw, pprctr, rsart, geber, fistl, matbf, ummab, bustm, bustw, mengu, wertu, lbkum, salk3, vprsv, fkber, dabrbz, vkwra, dabrz, xbeau, lsmng, lsmeh, kzbws, qinspst, urzei, j_1bexbase, mwskz, txjcd, ematn, j_1agirupd, vkmws, hsdat, berkz, mat_kdauf, mat_kdpos, mat_pspnr, xwoff, bemot, prznr, llief, lstar, xobew, grant_nbr, zustd_t156m, spe_gts_stock_ty, kblnr, kblpos, xmacc, vgart_mkpf, budat_mkpf, cpudt_mkpf, cputm_mkpf, usnam_mkpf, xblnr_mkpf, tcode2_mkpf, vbeln_im, vbelp_im, bev2_ed_kz_ver, bev2_ed_user, bev2_ed_aedat, bev2_ed_aetim, oinavnw, oicondcod, condi, sgt_scat, sgt_umscat, sgt_rcat, zztxjns, zztransdoc, zzjnsdoc, zztxtransid, zztxsts, zztxinvo, zztxdate, zzrepdoc, zzppn, last_insert_to_bigquery)
        SELECT
            CAST(mandt as STRING) as mandt,
            CAST(mblnr as STRING) as mblnr,
            CAST(mjahr as STRING) as mjahr,
            CAST(zeile as STRING) as zeile,
            CAST(line_id as STRING) as line_id,
            CAST(parent_id as STRING) as parent_id,
            CAST(line_depth as STRING) as line_depth,
            CAST(maa_urzei as STRING) as maa_urzei,
            CAST(bwart as STRING) as bwart,
            CAST(xauto as STRING) as xauto,
            CAST(matnr as STRING) as matnr,
            CAST(werks as STRING) as werks,
            CAST(lgort as STRING) as lgort,
            CAST(charg as STRING) as charg,
            CAST(insmk as STRING) as insmk,
            CAST(zusch as STRING) as zusch,
            CAST(zustd as STRING) as zustd,
            CAST(sobkz as STRING) as sobkz,
            CAST(lifnr as STRING) as lifnr,
            CAST(kunnr as STRING) as kunnr,
            CAST(kdauf as STRING) as kdauf,
            CAST(kdpos as STRING) as kdpos,
            CAST(kdein as STRING) as kdein,
            CAST(plpla as STRING) as plpla,
            CAST(shkzg as STRING) as shkzg,
            CAST(waers as STRING) as waers,
            CAST(dmbtr as STRING) as dmbtr,
            CAST(bnbtr as STRING) as bnbtr,
            CAST(bualt as STRING) as bualt,
            CAST(shkum as STRING) as shkum,
            CAST(dmbum as STRING) as dmbum,
            CAST(bwtar as STRING) as bwtar,
            CAST(menge as STRING) as menge,
            CAST(meins as STRING) as meins,
            CAST(erfmg as STRING) as erfmg,
            CAST(erfme as STRING) as erfme,
            CAST(bpmng as STRING) as bpmng,
            CAST(bprme as STRING) as bprme,
            CAST(ebeln as STRING) as ebeln,
            CAST(ebelp as STRING) as ebelp,
            CAST(lfbja as STRING) as lfbja,
            CAST(lfbnr as STRING) as lfbnr,
            CAST(lfpos as STRING) as lfpos,
            CAST(sjahr as STRING) as sjahr,
            CAST(smbln as STRING) as smbln,
            CAST(smblp as STRING) as smblp,
            CAST(elikz as STRING) as elikz,
            CAST(sgtxt as STRING) as sgtxt,
            CAST(equnr as STRING) as equnr,
            CAST(wempf as STRING) as wempf,
            CAST(ablad as STRING) as ablad,
            CAST(gsber as STRING) as gsber,
            CAST(kokrs as STRING) as kokrs,
            CAST(pargb as STRING) as pargb,
            CAST(parbu as STRING) as parbu,
            CAST(kostl as STRING) as kostl,
            CAST(projn as STRING) as projn,
            CAST(aufnr as STRING) as aufnr,
            CAST(anln1 as STRING) as anln1,
            CAST(anln2 as STRING) as anln2,
            CAST(xskst as STRING) as xskst,
            CAST(xsauf as STRING) as xsauf,
            CAST(xspro as STRING) as xspro,
            CAST(xserg as STRING) as xserg,
            CAST(gjahr as STRING) as gjahr,
            CAST(xruem as STRING) as xruem,
            CAST(xruej as STRING) as xruej,
            CAST(bukrs as STRING) as bukrs,
            CAST(belnr as STRING) as belnr,
            CAST(buzei as STRING) as buzei,
            CAST(belum as STRING) as belum,
            CAST(buzum as STRING) as buzum,
            CAST(rsnum as STRING) as rsnum,
            CAST(rspos as STRING) as rspos,
            CAST(kzear as STRING) as kzear,
            CAST(pbamg as STRING) as pbamg,
            CAST(kzstr as STRING) as kzstr,
            CAST(ummat as STRING) as ummat,
            CAST(umwrk as STRING) as umwrk,
            CAST(umlgo as STRING) as umlgo,
            CAST(umcha as STRING) as umcha,
            CAST(umzst as STRING) as umzst,
            CAST(umzus as STRING) as umzus,
            CAST(umbar as STRING) as umbar,
            CAST(umsok as STRING) as umsok,
            CAST(kzbew as STRING) as kzbew,
            CAST(kzvbr as STRING) as kzvbr,
            CAST(kzzug as STRING) as kzzug,
            CAST(weunb as STRING) as weunb,
            CAST(palan as STRING) as palan,
            CAST(lgnum as STRING) as lgnum,
            CAST(lgtyp as STRING) as lgtyp,
            CAST(lgpla as STRING) as lgpla,
            CAST(bestq as STRING) as bestq,
            CAST(bwlvs as STRING) as bwlvs,
            CAST(tbnum as STRING) as tbnum,
            CAST(tbpos as STRING) as tbpos,
            CAST(xblvs as STRING) as xblvs,
            CAST(vschn as STRING) as vschn,
            CAST(nschn as STRING) as nschn,
            CAST(dypla as STRING) as dypla,
            CAST(ubnum as STRING) as ubnum,
            CAST(tbpri as STRING) as tbpri,
            CAST(tanum as STRING) as tanum,
            CAST(weanz as STRING) as weanz,
            CAST(grund as STRING) as grund,
            CAST(evers as STRING) as evers,
            CAST(evere as STRING) as evere,
            CAST(imkey as STRING) as imkey,
            CAST(kstrg as STRING) as kstrg,
            CAST(paobjnr as STRING) as paobjnr,
            CAST(prctr as STRING) as prctr,
            CAST(ps_psp_pnr as STRING) as ps_psp_pnr,
            CAST(nplnr as STRING) as nplnr,
            CAST(aufpl as STRING) as aufpl,
            CAST(aplzl as STRING) as aplzl,
            CAST(aufps as STRING) as aufps,
            CAST(vptnr as STRING) as vptnr,
            CAST(fipos as STRING) as fipos,
            CAST(sakto as STRING) as sakto,
            CAST(bstmg as STRING) as bstmg,
            CAST(bstme as STRING) as bstme,
            CAST(xwsbr as STRING) as xwsbr,
            CAST(emlif as STRING) as emlif,
            CAST(exbwr as STRING) as exbwr,
            CAST(vkwrt as STRING) as vkwrt,
            CAST(aktnr as STRING) as aktnr,
            CAST(zekkn as STRING) as zekkn,
            CAST(vfdat as STRING) as vfdat,
            CAST(cuobj_ch as STRING) as cuobj_ch,
            CAST(exvkw as STRING) as exvkw,
            CAST(pprctr as STRING) as pprctr,
            CAST(rsart as STRING) as rsart,
            CAST(geber as STRING) as geber,
            CAST(fistl as STRING) as fistl,
            CAST(matbf as STRING) as matbf,
            CAST(ummab as STRING) as ummab,
            CAST(bustm as STRING) as bustm,
            CAST(bustw as STRING) as bustw,
            CAST(mengu as STRING) as mengu,
            CAST(wertu as STRING) as wertu,
            CAST(lbkum as STRING) as lbkum,
            CAST(salk3 as STRING) as salk3,
            CAST(vprsv as STRING) as vprsv,
            CAST(fkber as STRING) as fkber,
            CAST(dabrbz as STRING) as dabrbz,
            CAST(vkwra as STRING) as vkwra,
            CAST(dabrz as STRING) as dabrz,
            CAST(xbeau as STRING) as xbeau,
            CAST(lsmng as STRING) as lsmng,
            CAST(lsmeh as STRING) as lsmeh,
            CAST(kzbws as STRING) as kzbws,
            CAST(qinspst as STRING) as qinspst,
            CAST(urzei as STRING) as urzei,
            CAST(j_1bexbase as STRING) as j_1bexbase,
            CAST(mwskz as STRING) as mwskz,
            CAST(txjcd as STRING) as txjcd,
            CAST(ematn as STRING) as ematn,
            CAST(j_1agirupd as STRING) as j_1agirupd,
            CAST(vkmws as STRING) as vkmws,
            CAST(hsdat as STRING) as hsdat,
            CAST(berkz as STRING) as berkz,
            CAST(mat_kdauf as STRING) as mat_kdauf,
            CAST(mat_kdpos as STRING) as mat_kdpos,
            CAST(mat_pspnr as STRING) as mat_pspnr,
            CAST(xwoff as STRING) as xwoff,
            CAST(bemot as STRING) as bemot,
            CAST(prznr as STRING) as prznr,
            CAST(llief as STRING) as llief,
            CAST(lstar as STRING) as lstar,
            CAST(xobew as STRING) as xobew,
            CAST(grant_nbr as STRING) as grant_nbr,
            CAST(zustd_t156m as STRING) as zustd_t156m,
            CAST(spe_gts_stock_ty as STRING) as spe_gts_stock_ty,
            CAST(kblnr as STRING) as kblnr,
            CAST(kblpos as STRING) as kblpos,
            CAST(xmacc as STRING) as xmacc,
            CAST(vgart_mkpf as STRING) as vgart_mkpf,
            CAST(budat_mkpf as STRING) as budat_mkpf,
            CAST(cpudt_mkpf as STRING) as cpudt_mkpf,
            CAST(cputm_mkpf as STRING) as cputm_mkpf,
            CAST(usnam_mkpf as STRING) as usnam_mkpf,
            CAST(xblnr_mkpf as STRING) as xblnr_mkpf,
            CAST(tcode2_mkpf as STRING) as tcode2_mkpf,
            CAST(vbeln_im as STRING) as vbeln_im,
            CAST(vbelp_im as STRING) as vbelp_im,
            CAST(/bev2/ed_kz_ver as STRING) as bev2_ed_kz_ver,
            CAST(/bev2/ed_user as STRING) as bev2_ed_user,
            CAST(/bev2/ed_aedat as STRING) as bev2_ed_aedat,
            CAST(/bev2/ed_aetim as STRING) as bev2_ed_aetim,
            CAST(oinavnw as STRING) as oinavnw,
            CAST(oicondcod as STRING) as oicondcod,
            CAST(condi as STRING) as condi,
            CAST(sgt_scat as STRING) as sgt_scat,
            CAST(sgt_umscat as STRING) as sgt_umscat,
            CAST(sgt_rcat as STRING) as sgt_rcat,
            CAST(zztxjns as STRING) as zztxjns,
            CAST(zztransdoc as STRING) as zztransdoc,
            CAST(zzjnsdoc as STRING) as zzjnsdoc,
            CAST(zztxtransid as STRING) as zztxtransid,
            CAST(zztxsts as STRING) as zztxsts,
            CAST(zztxinvo as STRING) as zztxinvo,
            CAST(zztxdate as STRING) as zztxdate,
            CAST(zzrepdoc as STRING) as zzrepdoc,
            CAST(zzppn as STRING) as zzppn,
            DATETIME('{current_ts}') AS last_insert_to_bigquery
        FROM bq_landing_zone.{SCHEMA}_{TABLE};
    """

    # Execute pakai BigQueryInsertJobOperator
    BigQueryInsertJobOperator(
        task_id='load_to_refined_zone',
        gcp_conn_id='kai_genai_prod',
        configuration={
            "query": {
                "query": query,
                "useLegacySql": False,
            }
        },
        dag=kwargs['dag']
    ).execute(context=kwargs)
    
with models.DAG(
    'dashboard_material-mseg',
    description="Doing incremental load from PostgreSQL to GCS",
    start_date=pendulum.datetime(2024, 9, 30, tz="Asia/Jakarta"),
    schedule_interval='0 2 * * *',
    max_active_runs=1,
    catchup=False,
    tags=['Gen-AI', 'dashboard_material', 'refined'],
) as dag:

    dump_from_postgres_to_gcs = PostgresToGCSOperator(
        task_id='dump_from_postgres_to_gcs',
        postgres_conn_id=POSTGRES_CONNECTION_ID,
        sql=f"""
        SELECT
            "mandt"::TEXT as "mandt",
            "mblnr"::TEXT as "mblnr",
            "mjahr"::TEXT as "mjahr",
            "zeile"::TEXT as "zeile",
            "line_id"::TEXT as "line_id",
            "parent_id"::TEXT as "parent_id",
            "line_depth"::TEXT as "line_depth",
            "maa_urzei"::TEXT as "maa_urzei",
            "bwart"::TEXT as "bwart",
            "xauto"::TEXT as "xauto",
            "matnr"::TEXT as "matnr",
            "werks"::TEXT as "werks",
            "lgort"::TEXT as "lgort",
            "charg"::TEXT as "charg",
            "insmk"::TEXT as "insmk",
            "zusch"::TEXT as "zusch",
            "zustd"::TEXT as "zustd",
            "sobkz"::TEXT as "sobkz",
            "lifnr"::TEXT as "lifnr",
            "kunnr"::TEXT as "kunnr",
            "kdauf"::TEXT as "kdauf",
            "kdpos"::TEXT as "kdpos",
            "kdein"::TEXT as "kdein",
            "plpla"::TEXT as "plpla",
            "shkzg"::TEXT as "shkzg",
            "waers"::TEXT as "waers",
            "dmbtr"::INTEGER as "dmbtr",
            "bnbtr"::INTEGER as "bnbtr",
            "bualt"::INTEGER as "bualt",
            "shkum"::TEXT as "shkum",
            "dmbum"::INTEGER as "dmbum",
            "bwtar"::TEXT as "bwtar",
            "menge"::INTEGER as "menge",
            "meins"::TEXT as "meins",
            "erfmg"::INTEGER as "erfmg",
            "erfme"::TEXT as "erfme",
            "bpmng"::INTEGER as "bpmng",
            "bprme"::TEXT as "bprme",
            "ebeln"::TEXT as "ebeln",
            "ebelp"::TEXT as "ebelp",
            "lfbja"::TEXT as "lfbja",
            "lfbnr"::TEXT as "lfbnr",
            "lfpos"::TEXT as "lfpos",
            "sjahr"::TEXT as "sjahr",
            "smbln"::TEXT as "smbln",
            "smblp"::TEXT as "smblp",
            "elikz"::TEXT as "elikz",
            "sgtxt"::TEXT as "sgtxt",
            "equnr"::TEXT as "equnr",
            "wempf"::TEXT as "wempf",
            "ablad"::TEXT as "ablad",
            "gsber"::TEXT as "gsber",
            "kokrs"::TEXT as "kokrs",
            "pargb"::TEXT as "pargb",
            "parbu"::TEXT as "parbu",
            "kostl"::TEXT as "kostl",
            "projn"::TEXT as "projn",
            "aufnr"::TEXT as "aufnr",
            "anln1"::TEXT as "anln1",
            "anln2"::TEXT as "anln2",
            "xskst"::TEXT as "xskst",
            "xsauf"::TEXT as "xsauf",
            "xspro"::TEXT as "xspro",
            "xserg"::TEXT as "xserg",
            "gjahr"::TEXT as "gjahr",
            "xruem"::TEXT as "xruem",
            "xruej"::TEXT as "xruej",
            "bukrs"::TEXT as "bukrs",
            "belnr"::TEXT as "belnr",
            "buzei"::TEXT as "buzei",
            "belum"::TEXT as "belum",
            "buzum"::TEXT as "buzum",
            "rsnum"::TEXT as "rsnum",
            "rspos"::TEXT as "rspos",
            "kzear"::TEXT as "kzear",
            "pbamg"::INTEGER as "pbamg",
            "kzstr"::TEXT as "kzstr",
            "ummat"::TEXT as "ummat",
            "umwrk"::TEXT as "umwrk",
            "umlgo"::TEXT as "umlgo",
            "umcha"::TEXT as "umcha",
            "umzst"::TEXT as "umzst",
            "umzus"::TEXT as "umzus",
            "umbar"::TEXT as "umbar",
            "umsok"::TEXT as "umsok",
            "kzbew"::TEXT as "kzbew",
            "kzvbr"::TEXT as "kzvbr",
            "kzzug"::TEXT as "kzzug",
            "weunb"::TEXT as "weunb",
            "palan"::INTEGER as "palan",
            "lgnum"::TEXT as "lgnum",
            "lgtyp"::TEXT as "lgtyp",
            "lgpla"::TEXT as "lgpla",
            "bestq"::TEXT as "bestq",
            "bwlvs"::TEXT as "bwlvs",
            "tbnum"::TEXT as "tbnum",
            "tbpos"::TEXT as "tbpos",
            "xblvs"::TEXT as "xblvs",
            "vschn"::TEXT as "vschn",
            "nschn"::TEXT as "nschn",
            "dypla"::TEXT as "dypla",
            "ubnum"::TEXT as "ubnum",
            "tbpri"::TEXT as "tbpri",
            "tanum"::TEXT as "tanum",
            "weanz"::TEXT as "weanz",
            "grund"::TEXT as "grund",
            "evers"::TEXT as "evers",
            "evere"::TEXT as "evere",
            "imkey"::TEXT as "imkey",
            "kstrg"::TEXT as "kstrg",
            "paobjnr"::TEXT as "paobjnr",
            "prctr"::TEXT as "prctr",
            "ps_psp_pnr"::TEXT as "ps_psp_pnr",
            "nplnr"::TEXT as "nplnr",
            "aufpl"::TEXT as "aufpl",
            "aplzl"::TEXT as "aplzl",
            "aufps"::TEXT as "aufps",
            "vptnr"::TEXT as "vptnr",
            "fipos"::TEXT as "fipos",
            "sakto"::TEXT as "sakto",
            "bstmg"::INTEGER as "bstmg",
            "bstme"::TEXT as "bstme",
            "xwsbr"::TEXT as "xwsbr",
            "emlif"::TEXT as "emlif",
            "exbwr"::INTEGER as "exbwr",
            "vkwrt"::INTEGER as "vkwrt",
            "aktnr"::TEXT as "aktnr",
            "zekkn"::TEXT as "zekkn",
            "vfdat"::TEXT as "vfdat",
            "cuobj_ch"::TEXT as "cuobj_ch",
            "exvkw"::INTEGER as "exvkw",
            "pprctr"::TEXT as "pprctr",
            "rsart"::TEXT as "rsart",
            "geber"::TEXT as "geber",
            "fistl"::TEXT as "fistl",
            "matbf"::TEXT as "matbf",
            "ummab"::TEXT as "ummab",
            "bustm"::TEXT as "bustm",
            "bustw"::TEXT as "bustw",
            "mengu"::TEXT as "mengu",
            "wertu"::TEXT as "wertu",
            "lbkum"::TEXT as "lbkum",
            "salk3"::INTEGER as "salk3",
            "vprsv"::TEXT as "vprsv",
            "fkber"::TEXT as "fkber",
            "dabrbz"::TEXT as "dabrbz",
            "vkwra"::INTEGER as "vkwra",
            "dabrz"::TEXT as "dabrz",
            "xbeau"::TEXT as "xbeau",
            "lsmng"::INTEGER as "lsmng",
            "lsmeh"::TEXT as "lsmeh",
            "kzbws"::TEXT as "kzbws",
            "qinspst"::TEXT as "qinspst",
            "urzei"::TEXT as "urzei",
            "j_1bexbase"::INTEGER as "j_1bexbase",
            "mwskz"::TEXT as "mwskz",
            "txjcd"::TEXT as "txjcd",
            "ematn"::TEXT as "ematn",
            "j_1agirupd"::TEXT as "j_1agirupd",
            "vkmws"::TEXT as "vkmws",
            "hsdat"::TEXT as "hsdat",
            "berkz"::TEXT as "berkz",
            "mat_kdauf"::TEXT as "mat_kdauf",
            "mat_kdpos"::TEXT as "mat_kdpos",
            "mat_pspnr"::TEXT as "mat_pspnr",
            "xwoff"::TEXT as "xwoff",
            "bemot"::TEXT as "bemot",
            "prznr"::TEXT as "prznr",
            "llief"::TEXT as "llief",
            "lstar"::TEXT as "lstar",
            "xobew"::TEXT as "xobew",
            "grant_nbr"::TEXT as "grant_nbr",
            "zustd_t156m"::TEXT as "zustd_t156m",
            "spe_gts_stock_ty"::TEXT as "spe_gts_stock_ty",
            "kblnr"::TEXT as "kblnr",
            "kblpos"::TEXT as "kblpos",
            "xmacc"::TEXT as "xmacc",
            "vgart_mkpf"::TEXT as "vgart_mkpf",
            "budat_mkpf"::TEXT as "budat_mkpf",
            "cpudt_mkpf"::TEXT as "cpudt_mkpf",
            "cputm_mkpf"::TEXT as "cputm_mkpf",
            "usnam_mkpf"::TEXT as "usnam_mkpf",
            "xblnr_mkpf"::TEXT as "xblnr_mkpf",
            "tcode2_mkpf"::TEXT as "tcode2_mkpf",
            "vbeln_im"::TEXT as "vbeln_im",
            "vbelp_im"::TEXT as "vbelp_im",
            "/bev2/ed_kz_ver"::TEXT as "/bev2/ed_kz_ver",
            "/bev2/ed_user"::TEXT as "/bev2/ed_user",
            "/bev2/ed_aedat"::TEXT as "/bev2/ed_aedat",
            "/bev2/ed_aetim"::TEXT as "/bev2/ed_aetim",
            "oinavnw"::INTEGER as "oinavnw",
            "oicondcod"::TEXT as "oicondcod",
            "condi"::TEXT as "condi",
            "sgt_scat"::TEXT as "sgt_scat",
            "sgt_umscat"::TEXT as "sgt_umscat",
            "sgt_rcat"::TEXT as "sgt_rcat",
            "zztxjns"::TEXT as "zztxjns",
            "zztransdoc"::TEXT as "zztransdoc",
            "zzjnsdoc"::TEXT as "zzjnsdoc",
            "zztxtransid"::TEXT as "zztxtransid",
            "zztxsts"::TEXT as "zztxsts",
            "zztxinvo"::TEXT as "zztxinvo",
            "zztxdate"::TEXT as "zztxdate",
            "zzrepdoc"::TEXT as "zzrepdoc",
            "zzppn"::TEXT as "zzppn"
        FROM {SCHEMA}.{TABLE};
        """,
        bucket=GCS_BUCKET,
        filename=f'{SCHEMA}/{TABLE}/{FILE_NAME}',  # Nama file yang disimpan di GCS
        export_format='parquet',
        gcp_conn_id='kai_genai_prod',
        approx_max_file_size_bytes=20 * 1024 * 1024, # split 20 MB
        parquet_row_group_size=1000000,
    )

    load_to_bigquery = GoogleCloudStorageToBigQueryOperator(
        task_id='load_to_bigquery',
        bucket=GCS_BUCKET,
        source_objects=f'{SCHEMA}/{TABLE}/*',
        source_format='parquet',
        destination_project_dataset_table=f'{PROJECT_ID}.bq_landing_zone.{SCHEMA}_{TABLE}', # Dataset harus dibuat terlebih dahulu
        write_disposition='WRITE_TRUNCATE', # WRITE_TRUNCATE | WRITE_EMPTY
        skip_leading_rows=1,
        autodetect=True,
        gcp_conn_id='kai_genai_prod'
    )

    push_ts_task = PythonOperator(
        task_id='push_ts_task',
        python_callable=push_current_timestamp,
        provide_context=True
    )

    build_query_task = PythonOperator(
        task_id='build_query_task',
        python_callable=build_query_and_run,
        provide_context=True
    )

    show_progress = BashOperator(
        task_id='show_progress',
        bash_command='echo DAG finished at {{ ts_nodash }}'
    )

    # Dependency
    dump_from_postgres_to_gcs >> load_to_bigquery >> push_ts_task >> build_query_task >> show_progress
