# Kolom nya 400 cok

import pendulum

from airflow import models
from airflow.models import Variable
from airflow.providers.google.cloud.transfers.postgres_to_gcs import PostgresToGCSOperator
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.contrib.operators.gcs_to_bq import GoogleCloudStorageToBigQueryOperator
from airflow.operators.bash import BashOperator
from datetime import datetime
import pytz

PROJECT_ID = 'kai-genai-prod'
SCHEMA = 'dashboard_investasi'
POSTGRES_CONNECTION_ID = 'kai_postgres'
TABLE = 'mara'
GCS_BUCKET = 'kai_smartsheet'
FILE_NAME = f'{TABLE}.parquet'

def push_current_timestamp():
    jakarta_tz = pytz.timezone('Asia/Jakarta')
    current_ts = datetime.now(jakarta_tz).strftime('%Y-%m-%d %H:%M:%S')
    return current_ts  # Push to XCom automatically


def build_query_and_run(**kwargs):
    ti = kwargs['ti']
    current_ts = ti.xcom_pull(task_ids='push_ts_task')

    query = f"""
        CREATE or REPLACE TABLE {PROJECT_ID}.{SCHEMA}.{TABLE} as
        SELECT
            CAST(mandt as STRING) as mandt,
            CAST(matnr as STRING) as matnr,
            CAST(ersda as STRING) as ersda,
            CAST(ernam as STRING) as ernam,
            CAST(laeda as STRING) as laeda,
            CAST(aenam as STRING) as aenam,
            CAST(vpsta as STRING) as vpsta,
            CAST(pstat as STRING) as pstat,
            CAST(lvorm as STRING) as lvorm,
            CAST(mtart as STRING) as mtart,
            CAST(mbrsh as STRING) as mbrsh,
            CAST(matkl as STRING) as matkl,
            CAST(bismt as STRING) as bismt,
            CAST(meins as STRING) as meins,
            CAST(bstme as STRING) as bstme,
            CAST(zeinr as STRING) as zeinr,
            CAST(zeiar as STRING) as zeiar,
            CAST(zeivr as STRING) as zeivr,
            CAST(zeifo as STRING) as zeifo,
            CAST(aeszn as STRING) as aeszn,
            CAST(blatt as STRING) as blatt,
            CAST(blanz as STRING) as blanz,
            CAST(ferth as STRING) as ferth,
            CAST(formt as STRING) as formt,
            CAST(groes as STRING) as groes,
            CAST(wrkst as STRING) as wrkst,
            CAST(normt as STRING) as normt,
            CAST(labor as STRING) as labor,
            CAST(ekwsl as STRING) as ekwsl,
            CAST(brgew as NUMERIC) as brgew,
            CAST(ntgew as NUMERIC) as ntgew,
            CAST(gewei as STRING) as gewei,
            CAST(volum as NUMERIC) as volum,
            CAST(voleh as STRING) as voleh,
            CAST(behvo as STRING) as behvo,
            CAST(raube as STRING) as raube,
            CAST(tempb as STRING) as tempb,
            CAST(disst as STRING) as disst,
            CAST(tragr as STRING) as tragr,
            CAST(stoff as STRING) as stoff,
            CAST(spart as STRING) as spart,
            CAST(kunnr as STRING) as kunnr,
            CAST(eannr as STRING) as eannr,
            CAST(wesch as NUMERIC) as wesch,
            CAST(bwvor as STRING) as bwvor,
            CAST(bwscl as STRING) as bwscl,
            CAST(saiso as STRING) as saiso,
            CAST(etiar as STRING) as etiar,
            CAST(etifo as STRING) as etifo,
            CAST(entar as STRING) as entar,
            CAST(ean11 as STRING) as ean11,
            CAST(numtp as STRING) as numtp,
            CAST(laeng as NUMERIC) as laeng,
            CAST(breit as NUMERIC) as breit,
            CAST(hoehe as NUMERIC) as hoehe,
            CAST(meabm as STRING) as meabm,
            CAST(prdha as STRING) as prdha,
            CAST(aeklk as STRING) as aeklk,
            CAST(cadkz as STRING) as cadkz,
            CAST(qmpur as STRING) as qmpur,
            CAST(ergew as NUMERIC) as ergew,
            CAST(ergei as STRING) as ergei,
            CAST(ervol as NUMERIC) as ervol,
            CAST(ervoe as STRING) as ervoe,
            CAST(gewto as NUMERIC) as gewto,
            CAST(volto as NUMERIC) as volto,
            CAST(vabme as STRING) as vabme,
            CAST(kzrev as STRING) as kzrev,
            CAST(kzkfg as STRING) as kzkfg,
            CAST(xchpf as STRING) as xchpf,
            CAST(vhart as STRING) as vhart,
            CAST(fuelg as INTEGER) as fuelg,
            CAST(stfak as INTEGER) as stfak,
            CAST(magrv as STRING) as magrv,
            CAST(begru as STRING) as begru,
            CAST(datab as STRING) as datab,
            CAST(liqdt as STRING) as liqdt,
            CAST(saisj as STRING) as saisj,
            CAST(plgtp as STRING) as plgtp,
            CAST(mlgut as STRING) as mlgut,
            CAST(extwg as STRING) as extwg,
            CAST(satnr as STRING) as satnr,
            CAST(attyp as STRING) as attyp,
            CAST(kzkup as STRING) as kzkup,
            CAST(kznfm as STRING) as kznfm,
            CAST(pmata as STRING) as pmata,
            CAST(mstae as STRING) as mstae,
            CAST(mstav as STRING) as mstav,
            CAST(mstde as STRING) as mstde,
            CAST(mstdv as STRING) as mstdv,
            CAST(taklv as STRING) as taklv,
            CAST(rbnrm as STRING) as rbnrm,
            CAST(mhdrz as INTEGER) as mhdrz,
            CAST(mhdhb as INTEGER) as mhdhb,
            CAST(mhdlp as INTEGER) as mhdlp,
            CAST(inhme as STRING) as inhme,
            CAST(inhal as NUMERIC) as inhal,
            CAST(vpreh as INTEGER) as vpreh,
            CAST(etiag as STRING) as etiag,
            CAST(inhbr as NUMERIC) as inhbr,
            CAST(cmeth as STRING) as cmeth,
            CAST(cuobf as STRING) as cuobf,
            CAST(kzumw as STRING) as kzumw,
            CAST(kosch as STRING) as kosch,
            CAST(sprof as STRING) as sprof,
            CAST(nrfhg as STRING) as nrfhg,
            CAST(mfrpn as STRING) as mfrpn,
            CAST(mfrnr as STRING) as mfrnr,
            CAST(bmatn as STRING) as bmatn,
            CAST(mprof as STRING) as mprof,
            CAST(kzwsm as STRING) as kzwsm,
            CAST(saity as STRING) as saity,
            CAST(profl as STRING) as profl,
            CAST(ihivi as STRING) as ihivi,
            CAST(iloos as STRING) as iloos,
            CAST(serlv as STRING) as serlv,
            CAST(kzgvh as STRING) as kzgvh,
            CAST(xgchp as STRING) as xgchp,
            CAST(kzeff as STRING) as kzeff,
            CAST(compl as STRING) as compl,
            CAST(iprkz as STRING) as iprkz,
            CAST(rdmhd as STRING) as rdmhd,
            CAST(przus as STRING) as przus,
            CAST(mtpos_mara as STRING) as mtpos_mara,
            CAST(bflme as STRING) as bflme,
            CAST(matfi as STRING) as matfi,
            CAST(cmrel as STRING) as cmrel,
            CAST(bbtyp as STRING) as bbtyp,
            CAST(sled_bbd as STRING) as sled_bbd,
            CAST(gtin_variant as STRING) as gtin_variant,
            CAST(gennr as STRING) as gennr,
            CAST(rmatp as STRING) as rmatp,
            CAST(gds_relevant as STRING) as gds_relevant,
            CAST(weora as STRING) as weora,
            CAST(hutyp_dflt as STRING) as hutyp_dflt,
            CAST(pilferable as STRING) as pilferable,
            CAST(whstc as STRING) as whstc,
            CAST(whmatgr as STRING) as whmatgr,
            CAST(hndlcode as STRING) as hndlcode,
            CAST(hazmat as STRING) as hazmat,
            CAST(hutyp as STRING) as hutyp,
            CAST(tare_var as STRING) as tare_var,
            CAST(maxc as NUMERIC) as maxc,
            CAST(maxc_tol as NUMERIC) as maxc_tol,
            CAST(maxl as NUMERIC) as maxl,
            CAST(maxb as NUMERIC) as maxb,
            CAST(maxh as NUMERIC) as maxh,
            CAST(maxdim_uom as STRING) as maxdim_uom,
            CAST(herkl as STRING) as herkl,
            CAST(mfrgr as STRING) as mfrgr,
            CAST(qqtime as INTEGER) as qqtime,
            CAST(qqtimeuom as STRING) as qqtimeuom,
            CAST(qgrp as STRING) as qgrp,
            CAST(serial as STRING) as serial,
            CAST(ps_smartform as STRING) as ps_smartform,
            CAST(logunit as STRING) as logunit,
            CAST(cwqrel as STRING) as cwqrel,
            CAST(cwqproc as STRING) as cwqproc,
            CAST(cwqtolgr as STRING) as cwqtolgr,
            CAST(adprof as STRING) as adprof,
            CAST(ipmipproduct as STRING) as ipmipproduct,
            CAST(allow_pmat_igno as STRING) as allow_pmat_igno,
            CAST(medium as STRING) as medium,
            CAST(animal_origin as STRING) as animal_origin,
            CAST(textile_comp_ind as STRING) as textile_comp_ind,
            CAST(anp as STRING) as anp,
            CAST(BEV1_LULEINH as STRING) as BEV1_LULEINH,
            CAST(BEV1_LULDEGRP as STRING) as BEV1_LULDEGRP,
            CAST(BEV1_NESTRUCCAT as STRING) as BEV1_NESTRUCCAT,
            CAST(DSD_SL_TOLTYP as STRING) as DSD_SL_TOLTYP,
            CAST(DSD_SV_CNT_GRP as STRING) as DSD_SV_CNT_GRP,
            CAST(DSD_VC_GROUP as STRING) as DSD_VC_GROUP,
            CAST(VSO_R_TILT_IND as STRING) as VSO_R_TILT_IND,
            CAST(VSO_R_STACK_IND as STRING) as VSO_R_STACK_IND,
            CAST(VSO_R_BOT_IND as STRING) as VSO_R_BOT_IND,
            CAST(VSO_R_TOP_IND as STRING) as VSO_R_TOP_IND,
            CAST(VSO_R_STACK_NO as STRING) as VSO_R_STACK_NO,
            CAST(VSO_R_PAL_IND as STRING) as VSO_R_PAL_IND,
            CAST(VSO_R_PAL_OVR_D as NUMERIC) as VSO_R_PAL_OVR_D,
            CAST(VSO_R_PAL_OVR_W as NUMERIC) as VSO_R_PAL_OVR_W,
            CAST(VSO_R_PAL_B_HT as NUMERIC) as VSO_R_PAL_B_HT,
            CAST(VSO_R_PAL_MIN_H as NUMERIC) as VSO_R_PAL_MIN_H,
            CAST(VSO_R_TOL_B_HT as NUMERIC) as VSO_R_TOL_B_HT,
            CAST(VSO_R_NO_P_GVH as STRING) as VSO_R_NO_P_GVH,
            CAST(VSO_R_QUAN_UNIT as STRING) as VSO_R_QUAN_UNIT,
            CAST(VSO_R_KZGVH_IND as STRING) as VSO_R_KZGVH_IND,
            CAST(packcode as STRING) as packcode,
            CAST(dg_pack_status as STRING) as dg_pack_status,
            CAST(mcond as STRING) as mcond,
            CAST(retdelc as STRING) as retdelc,
            CAST(loglev_reto as STRING) as loglev_reto,
            CAST(nsnid as STRING) as nsnid,
            CAST(imatn as STRING) as imatn,
            CAST(picnum as STRING) as picnum,
            CAST(bstat as STRING) as bstat,
            CAST(color_atinn as STRING) as color_atinn,
            CAST(size1_atinn as STRING) as size1_atinn,
            CAST(size2_atinn as STRING) as size2_atinn,
            CAST(color as STRING) as color,
            CAST(size1 as STRING) as size1,
            CAST(size2 as STRING) as size2,
            CAST(free_char as STRING) as free_char,
            CAST(care_code as STRING) as care_code,
            CAST(brand_id as STRING) as brand_id,
            CAST(fiber_code1 as STRING) as fiber_code1,
            CAST(fiber_part1 as STRING) as fiber_part1,
            CAST(fiber_code2 as STRING) as fiber_code2,
            CAST(fiber_part2 as STRING) as fiber_part2,
            CAST(fiber_code3 as STRING) as fiber_code3,
            CAST(fiber_part3 as STRING) as fiber_part3,
            CAST(fiber_code4 as STRING) as fiber_code4,
            CAST(fiber_part4 as STRING) as fiber_part4,
            CAST(fiber_code5 as STRING) as fiber_code5,
            CAST(fiber_part5 as STRING) as fiber_part5,
            CAST(fashgrd as STRING) as fashgrd,
            CAST(commodity as STRING) as commodity,
            CAST(sgt_csgr as STRING) as sgt_csgr,
            CAST(sgt_covsa as STRING) as sgt_covsa,
            CAST(sgt_stat as STRING) as sgt_stat,
            CAST(sgt_scope as STRING) as sgt_scope,
            CAST(sgt_rel as STRING) as sgt_rel,
            CAST(fsh_mg_at1 as STRING) as fsh_mg_at1,
            CAST(fsh_mg_at2 as STRING) as fsh_mg_at2,
            CAST(fsh_mg_at3 as STRING) as fsh_mg_at3,
            CAST(fsh_sealv as STRING) as fsh_sealv,
            CAST(fsh_seaim as STRING) as fsh_seaim,
            CAST(fsh_sc_mid as STRING) as fsh_sc_mid,
            CAST(psm_code as STRING) as psm_code,
            TIMESTAMP('{current_ts}') AS last_insert_to_bigquery
        FROM bq_landing_zone.{SCHEMA}_{TABLE};
    """

    # Execute pakai BigQueryInsertJobOperator
    BigQueryInsertJobOperator(
        task_id='load_to_refined_zone',
        gcp_conn_id='kai_genai_prod',
        configuration={
            "query": {
                "query": query,
                "useLegacySql": False,
            }
        },
        dag=kwargs['dag']
    ).execute(context=kwargs)
    
with models.DAG(
    'dashboard_investasi-mara',
    description="Doing incremental load from PostgreSQL to GCS",
    start_date=pendulum.datetime(2024, 9, 30, tz="Asia/Jakarta"),
    schedule_interval='* 1 * * *',
    max_active_runs=1,
    catchup=False,
    tags=['Gen-AI', 'dashboard_investasi', 'refined'],
) as dag:

    dump_from_postgres_to_gcs = PostgresToGCSOperator(
        task_id='dump_from_postgres_to_gcs',
        postgres_conn_id=POSTGRES_CONNECTION_ID,
        sql=f"""
        SELECT
            "mandt"::TEXT as "mandt",
            "matnr"::TEXT as "matnr",
            "ersda"::TEXT as "ersda",
            "ernam"::TEXT as "ernam",
            "laeda"::TEXT as "laeda",
            "aenam"::TEXT as "aenam",
            "vpsta"::TEXT as "vpsta",
            "pstat"::TEXT as "pstat",
            "lvorm"::TEXT as "lvorm",
            "mtart"::TEXT as "mtart",
            "mbrsh"::TEXT as "mbrsh",
            "matkl"::TEXT as "matkl",
            "bismt"::TEXT as "bismt",
            "meins"::TEXT as "meins",
            "bstme"::TEXT as "bstme",
            "zeinr"::TEXT as "zeinr",
            "zeiar"::TEXT as "zeiar",
            "zeivr"::TEXT as "zeivr",
            "zeifo"::TEXT as "zeifo",
            "aeszn"::TEXT as "aeszn",
            "blatt"::TEXT as "blatt",
            "blanz"::TEXT as "blanz",
            "ferth"::TEXT as "ferth",
            "formt"::TEXT as "formt",
            "groes"::TEXT as "groes",
            "wrkst"::TEXT as "wrkst",
            "normt"::TEXT as "normt",
            "labor"::TEXT as "labor",
            "ekwsl"::TEXT as "ekwsl",
            "brgew"::NUMERIC as "brgew",
            "ntgew"::NUMERIC as "ntgew",
            "gewei"::TEXT as "gewei",
            "volum"::NUMERIC as "volum",
            "voleh"::TEXT as "voleh",
            "behvo"::TEXT as "behvo",
            "raube"::TEXT as "raube",
            "tempb"::TEXT as "tempb",
            "disst"::TEXT as "disst",
            "tragr"::TEXT as "tragr",
            "stoff"::TEXT as "stoff",
            "spart"::TEXT as "spart",
            "kunnr"::TEXT as "kunnr",
            "eannr"::TEXT as "eannr",
            "wesch"::NUMERIC as "wesch",
            "bwvor"::TEXT as "bwvor",
            "bwscl"::TEXT as "bwscl",
            "saiso"::TEXT as "saiso",
            "etiar"::TEXT as "etiar",
            "etifo"::TEXT as "etifo",
            "entar"::TEXT as "entar",
            "ean11"::TEXT as "ean11",
            "numtp"::TEXT as "numtp",
            "laeng"::NUMERIC as "laeng",
            "breit"::NUMERIC as "breit",
            "hoehe"::NUMERIC as "hoehe",
            "meabm"::TEXT as "meabm",
            "prdha"::TEXT as "prdha",
            "aeklk"::TEXT as "aeklk",
            "cadkz"::TEXT as "cadkz",
            "qmpur"::TEXT as "qmpur",
            "ergew"::NUMERIC as "ergew",
            "ergei"::TEXT as "ergei",
            "ervol"::NUMERIC as "ervol",
            "ervoe"::TEXT as "ervoe",
            "gewto"::NUMERIC as "gewto",
            "volto"::NUMERIC as "volto",
            "vabme"::TEXT as "vabme",
            "kzrev"::TEXT as "kzrev",
            "kzkfg"::TEXT as "kzkfg",
            "xchpf"::TEXT as "xchpf",
            "vhart"::TEXT as "vhart",
            "fuelg"::INT as "fuelg",
            "stfak"::INT as "stfak",
            "magrv"::TEXT as "magrv",
            "begru"::TEXT as "begru",
            "datab"::TEXT as "datab",
            "liqdt"::TEXT as "liqdt",
            "saisj"::TEXT as "saisj",
            "plgtp"::TEXT as "plgtp",
            "mlgut"::TEXT as "mlgut",
            "extwg"::TEXT as "extwg",
            "satnr"::TEXT as "satnr",
            "attyp"::TEXT as "attyp",
            "kzkup"::TEXT as "kzkup",
            "kznfm"::TEXT as "kznfm",
            "pmata"::TEXT as "pmata",
            "mstae"::TEXT as "mstae",
            "mstav"::TEXT as "mstav",
            "mstde"::TEXT as "mstde",
            "mstdv"::TEXT as "mstdv",
            "taklv"::TEXT as "taklv",
            "rbnrm"::TEXT as "rbnrm",
            "mhdrz"::INT as "mhdrz",
            "mhdhb"::INT as "mhdhb",
            "mhdlp"::INT as "mhdlp",
            "inhme"::TEXT as "inhme",
            "inhal"::NUMERIC as "inhal",
            "vpreh"::INT as "vpreh",
            "etiag"::TEXT as "etiag",
            "inhbr"::NUMERIC as "inhbr",
            "cmeth"::TEXT as "cmeth",
            "cuobf"::TEXT as "cuobf",
            "kzumw"::TEXT as "kzumw",
            "kosch"::TEXT as "kosch",
            "sprof"::TEXT as "sprof",
            "nrfhg"::TEXT as "nrfhg",
            "mfrpn"::TEXT as "mfrpn",
            "mfrnr"::TEXT as "mfrnr",
            "bmatn"::TEXT as "bmatn",
            "mprof"::TEXT as "mprof",
            "kzwsm"::TEXT as "kzwsm",
            "saity"::TEXT as "saity",
            "profl"::TEXT as "profl",
            "ihivi"::TEXT as "ihivi",
            "iloos"::TEXT as "iloos",
            "serlv"::TEXT as "serlv",
            "kzgvh"::TEXT as "kzgvh",
            "xgchp"::TEXT as "xgchp",
            "kzeff"::TEXT as "kzeff",
            "compl"::TEXT as "compl",
            "iprkz"::TEXT as "iprkz",
            "rdmhd"::TEXT as "rdmhd",
            "przus"::TEXT as "przus",
            "mtpos_mara"::TEXT as "mtpos_mara",
            "bflme"::TEXT as "bflme",
            "matfi"::TEXT as "matfi",
            "cmrel"::TEXT as "cmrel",
            "bbtyp"::TEXT as "bbtyp",
            "sled_bbd"::TEXT as "sled_bbd",
            "gtin_variant"::TEXT as "gtin_variant",
            "gennr"::TEXT as "gennr",
            "rmatp"::TEXT as "rmatp",
            "gds_relevant"::TEXT as "gds_relevant",
            "weora"::TEXT as "weora",
            "hutyp_dflt"::TEXT as "hutyp_dflt",
            "pilferable"::TEXT as "pilferable",
            "whstc"::TEXT as "whstc",
            "whmatgr"::TEXT as "whmatgr",
            "hndlcode"::TEXT as "hndlcode",
            "hazmat"::TEXT as "hazmat",
            "hutyp"::TEXT as "hutyp",
            "tare_var"::TEXT as "tare_var",
            "maxc"::NUMERIC as "maxc",
            "maxc_tol"::NUMERIC as "maxc_tol",
            "maxl"::NUMERIC as "maxl",
            "maxb"::NUMERIC as "maxb",
            "maxh"::NUMERIC as "maxh",
            "maxdim_uom"::TEXT as "maxdim_uom",
            "herkl"::TEXT as "herkl",
            "mfrgr"::TEXT as "mfrgr",
            "qqtime"::INT as "qqtime",
            "qqtimeuom"::TEXT as "qqtimeuom",
            "qgrp"::TEXT as "qgrp",
            "serial"::TEXT as "serial",
            "ps_smartform"::TEXT as "ps_smartform",
            "logunit"::TEXT as "logunit",
            "cwqrel"::TEXT as "cwqrel",
            "cwqproc"::TEXT as "cwqproc",
            "cwqtolgr"::TEXT as "cwqtolgr",
            "adprof"::TEXT as "adprof",
            "ipmipproduct"::TEXT as "ipmipproduct",
            "allow_pmat_igno"::TEXT as "allow_pmat_igno",
            "medium"::TEXT as "medium",
            "animal_origin"::TEXT as "animal_origin",
            "textile_comp_ind"::TEXT as "textile_comp_ind",
            "anp"::TEXT as "anp",
            "/BEV1/LULEINH"::TEXT as "BEV1_LULEINH",
            "/BEV1/LULDEGRP"::TEXT as "BEV1_LULDEGRP",
            "/BEV1/NESTRUCCAT"::TEXT as "BEV1_NESTRUCCAT",
            "/DSD/SL_TOLTYP"::TEXT as "DSD_SL_TOLTYP",
            "/DSD/SV_CNT_GRP"::TEXT as "DSD_SV_CNT_GRP",
            "/DSD/VC_GROUP"::TEXT as "DSD_VC_GROUP",
            "/VSO/R_TILT_IND"::TEXT as "VSO_R_TILT_IND",
            "/VSO/R_STACK_IND"::TEXT as "VSO_R_STACK_IND",
            "/VSO/R_BOT_IND"::TEXT as "VSO_R_BOT_IND",
            "/VSO/R_TOP_IND"::TEXT as "VSO_R_TOP_IND",
            "/VSO/R_STACK_NO"::TEXT as "VSO_R_STACK_NO",
            "/VSO/R_PAL_IND"::TEXT as "VSO_R_PAL_IND",
            "/VSO/R_PAL_OVR_D"::NUMERIC as "VSO_R_PAL_OVR_D",
            "/VSO/R_PAL_OVR_W"::NUMERIC as "VSO_R_PAL_OVR_W",
            "/VSO/R_PAL_B_HT"::NUMERIC as "VSO_R_PAL_B_HT",
            "/VSO/R_PAL_MIN_H"::NUMERIC as "VSO_R_PAL_MIN_H",
            "/VSO/R_TOL_B_HT"::NUMERIC as "VSO_R_TOL_B_HT",
            "/VSO/R_NO_P_GVH"::TEXT as "VSO_R_NO_P_GVH",
            "/VSO/R_QUAN_UNIT"::TEXT as "VSO_R_QUAN_UNIT",
            "/VSO/R_KZGVH_IND"::TEXT as "VSO_R_KZGVH_IND",
            "packcode"::TEXT as "packcode",
            "dg_pack_status"::TEXT as "dg_pack_status",
            "mcond"::TEXT as "mcond",
            "retdelc"::TEXT as "retdelc",
            "loglev_reto"::TEXT as "loglev_reto",
            "nsnid"::TEXT as "nsnid",
            "imatn"::TEXT as "imatn",
            "picnum"::TEXT as "picnum",
            "bstat"::TEXT as "bstat",
            "color_atinn"::TEXT as "color_atinn",
            "size1_atinn"::TEXT as "size1_atinn",
            "size2_atinn"::TEXT as "size2_atinn",
            "color"::TEXT as "color",
            "size1"::TEXT as "size1",
            "size2"::TEXT as "size2",
            "free_char"::TEXT as "free_char",
            "care_code"::TEXT as "care_code",
            "brand_id"::TEXT as "brand_id",
            "fiber_code1"::TEXT as "fiber_code1",
            "fiber_part1"::TEXT as "fiber_part1",
            "fiber_code2"::TEXT as "fiber_code2",
            "fiber_part2"::TEXT as "fiber_part2",
            "fiber_code3"::TEXT as "fiber_code3",
            "fiber_part3"::TEXT as "fiber_part3",
            "fiber_code4"::TEXT as "fiber_code4",
            "fiber_part4"::TEXT as "fiber_part4",
            "fiber_code5"::TEXT as "fiber_code5",
            "fiber_part5"::TEXT as "fiber_part5",
            "fashgrd"::TEXT as "fashgrd",
            "commodity"::TEXT as "commodity",
            "sgt_csgr"::TEXT as "sgt_csgr",
            "sgt_covsa"::TEXT as "sgt_covsa",
            "sgt_stat"::TEXT as "sgt_stat",
            "sgt_scope"::TEXT as "sgt_scope",
            "sgt_rel"::TEXT as "sgt_rel",
            "fsh_mg_at1"::TEXT as "fsh_mg_at1",
            "fsh_mg_at2"::TEXT as "fsh_mg_at2",
            "fsh_mg_at3"::TEXT as "fsh_mg_at3",
            "fsh_sealv"::TEXT as "fsh_sealv",
            "fsh_seaim"::TEXT as "fsh_seaim",
            "fsh_sc_mid"::TEXT as "fsh_sc_mid",
            "psm_code"::TEXT as "psm_code"
        FROM {SCHEMA}.{TABLE};
        """,
        bucket=GCS_BUCKET,
        filename=f'{SCHEMA}/{TABLE}/{FILE_NAME}',  # Nama file yang disimpan di GCS
        export_format='parquet',
        gcp_conn_id='kai_genai_prod',
        approx_max_file_size_bytes=50 * 1024 * 1024, # split 50 MB
        # parquet_row_group_size=1000000,
    )

    load_to_bigquery = GoogleCloudStorageToBigQueryOperator(
        task_id='load_to_bigquery',
        bucket=GCS_BUCKET,
        source_objects=f'{SCHEMA}/{TABLE}/{FILE_NAME}',
        source_format='parquet',
        destination_project_dataset_table=f'{PROJECT_ID}.bq_landing_zone.{SCHEMA}_{TABLE}', # Dataset harus dibuat terlebih dahulu
        write_disposition='WRITE_TRUNCATE', # WRITE_TRUNCATE | WRITE_EMPTY
        skip_leading_rows=1,
        autodetect=True,
        gcp_conn_id='kai_genai_prod'
    )

    push_ts_task = PythonOperator(
        task_id='push_ts_task',
        python_callable=push_current_timestamp,
        provide_context=True
    )

    build_query_task = PythonOperator(
        task_id='build_query_task',
        python_callable=build_query_and_run,
        provide_context=True
    )

    show_progress = BashOperator(
        task_id='show_progress',
        bash_command='echo DAG finished at {{ ts_nodash }}'
    )

    # Dependency
    dump_from_postgres_to_gcs >> load_to_bigquery >> push_ts_task >> build_query_task >> show_progress
